name: Deploy to TNP Portal

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_nitp_TNP
          chmod 600 ~/.ssh/id_nitp_TNP
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Run deploy script on EC2
        run: |
          ssh -i ~/.ssh/id_nitp_TNP ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'sudo bash -c "cd /root && ./latest_tnp_deploy.sh"'